%YAML:1.0
---
rotationDegrees: 0
cannyThreshold1: 160
cannyThreshold2: 260
digitMinHeight: 3.9999995380640030e-02
digitMaxHeight: 6.5000005066394806e-02
digitYAlignment: 20
ocrMaxDist: 500000.
trainingDataFilename: "trainctr.yml"
